### ISSUE TITLE
Reduce logging when old secrets are accepted

### ISSUE THREAD

**Issue by amyhughes** [guardian/play-secret-rotation#1]
We've just updated a secret for Ophan Dashboard with this library without a hitch ;-)

One possible improvement - the logging when accepting old secrets is a little numerous for the number of times this happens:
 
![image](https://user-images.githubusercontent.com/9820960/38432719-5b999b54-39c0-11e8-8e15-792ce31245f1.png)

Perhaps the logging should only be at debug level for the first bit of the overlap period, and info level after this?

**Comment by rtyley** [comment]
Closed by #2727.
