### ISSUE TITLE
`CSRFTokenSigner` freezes its copy of the secret on startup, leads to unpredictable CSRF token rejection

### ISSUE THREAD

**Issue by rtyley** [guardian/play-secret-rotation#445]
Investigating https://github.com/guardian/ophan/issues/5970, which was seeing many of these errors:

```
[CSRF] Check failed because no token found in headers for /tester/device-authorisation/process
```

...it's become clear that `play-secret-rotation`, which overrides the crucial `RequestFactory` component to adopt secret-rotating behaviour with `RotatingSecretComponents`:

https://github.com/guardian/play-secret-rotation/blob/4c96b9294e30f231713a79a0cb449668c81c7eba/play/play-v27/RotatingSecretComponents.scala#L22-L23

..._doesn't_ also override `CSRFTokenSigner`.

Consequently, if app servers in a cluster have started at different times, before and after a secret rotation, as in [this case](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(view~'timeSeries~stacked~false~start~'2024-03-20T05*3a55*3a00.549Z~end~'2024-03-21T17*3a05*3a00.745Z~region~'eu-west-1~metrics~(~(~'AWS*2fEC2~'CPUUtilization~'InstanceId~'i-0d81cc09075ec1078)~(~'...~'i-0dac56c6af2dbfdae))~annotations~(vertical~(~(label~'Secret*20rotation~value~'2024-03-20T14*3a24*3a32.000Z)~(color~'*23d62728~label~'Secret*20rotation~value~'2024-03-20T20*3a24*3a32.000Z)~(color~'*23d62728~label~'Secret*20rotation~value~'2024-03-20T08*3a24*3a32.000Z))))&query=~'*7bAWS*2fEC2*2cInstanceId*7d*20i-0dac56c6af2dbfdae) with the Ophan Dashboard:

![image](https://github.com/guardian/play-secret-rotation/assets/52038/eafa2cec-8fa8-4e27-b5b5-b3e07d51c4d1)

...then different servers within a Play app server cluster will be using a _different_ secret for signing the CSRF token - and consequently reject each others tokens. If a user is making a form-POST-ing request, it's a random chance as to whether their POST will be received by a Play server instance using the same secret as the form was created with - a random chance whether it will fail.

**Comment by SHession** [comment]
To be clear about the cause of the issue. Was the `CSRFTokenSigner` failing to validate old keys or rotate them to new ones or both?

**Comment by rtyley** [comment]
> To be clear about the cause of the issue. Was the `CSRFTokenSigner` failing to validate old keys or rotate them to new ones or both?

The second one - `CSRFTokenSigner` was never updating the secret it was using to sign or verify tokens. The secret it used was entirely dependent on when that EC2 instance started up.
